# Generated by Django 4.2 on 2023-04-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cliq',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
