# Generated by Django 4.2 on 2023-05-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_products_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='hot_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, to='products.products')),
            ],
        ),
    ]
