# Generated by Django 4.2 on 2023-05-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_edition'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, to='products.products')),
            ],
        ),
    ]
