# Generated by Django 4.2 on 2023-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=10000)),
                ('discription', models.TextField(max_length=100000)),
                ('Sdiscription', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=40)),
                ('stock', models.IntegerField(max_length=100)),
            ],
        ),
    ]
