# Generated by Django 4.2.1 on 2023-05-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_orderitem_orders_orderitem_order_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='products.products'),
        ),
    ]
