# Generated by Django 4.2 on 2023-05-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_products_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
