# Generated by Django 4.2 on 2023-05-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_is_hidden_products_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='edition',
            field=models.CharField(default='Standard Edition', max_length=100),
            preserve_default=False,
        ),
    ]
