# Generated by Django 4.2 on 2023-05-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_orders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phonen',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
